### ISSUE TITLE
ResolutionException

### ISSUE THREAD

**Issue by sankintoo** [bertramn/cxf-jackson-osgi-blueprint-issue#1]
Hello,
I am trying you example.
following error is seen. I am not sure why is this occuring. could you please assist.

osgi.service.resolver.ResolutionException: Unable to resolve root: missing requirement [root] osgi.identity; osgi.identity=cxf-jackson-example-all; type=karaf.feature; version="[1.0.0,1.0.0]"; filter:="(&(osgi.identity=cxf-jackson-example-all)(type=karaf.feature)(version>=1.0.0)(version<=1.0.0))" [caused by: Unable to resolve cxf-jackson-example-all/1.0.0: missing requirement [cxf-jackson-example-all/1.0.0] osgi.identity; osgi.identity=io.github.bertramn.cxf-jackson-osgi-blueprint-issue; type=osgi.bundle; version="[1.0.0,1.0.0]"; resolution:=mandatory [caused by: Unable to resolve io.github.bertramn.cxf-jackson-osgi-blueprint-issue/1.0.0: missing requirement [io.github.bertramn.cxf-jackson-osgi-blueprint-issue/1.0.0] osgi.wiring.package; filter:="(&(osgi.wiring.package=org.osgi.service.blueprint)(version>=1.0.0)(!(version>=2.0.0)))"]]
	at org.apache.felix.resolver.ResolutionError.toException(ResolutionError.java:42) ~[?:?]

**Comment by bertramn** [comment]
No idea what the issue is, probably best for you to post questions about Felix resolver to the [Karaf user forum](https://karaf.apache.org/community.html).
